import TableCtrl from '@/components/common/TableCtrl';
import { DownloadOutlined } from '@ant-design/icons';

const btns = [
  {
    alias: '导出',
    handleClick: () => {},
    icon: <DownloadOutlined />,
    name: 'export',
    type: 'primary',
    others: {
      style: { float: 'right', marginBottom: '8px' },
    },
  },
];
const table = {
  columns: [
    {
      title: '序号',
      dataIndex: 'gid',
      key: 'gid',
      width: 50,
      ellipsis: true,
      render: (text, record, index) => {
        return <span>{index + 1}</span>;
      },
    },
    {
      title: '记分来源',
      dataIndex: 'scoreSource',
      key: 'scoreSource',
      width: 120,
      ellipsis: true,
    },
    {
      title: '发起记分单位',
      dataIndex: 'initiateScoreCompany',
      key: 'initiateScoreCompany',
      ellipsis: true,
    },
    {
      title: '发起记分人',
      dataIndex: 'initiateScoreUsername',
      key: 'initiateScoreUsername',
      width: 120,
      ellipsis: true,
    },
    {
      title: '记分日期',
      dataIndex: 'initiateScore',
      key: 'initiateScore',
      width: 130,
      ellipsis: true,
    },
    {
      title: '记分事项',
      dataIndex: 'item',
      key: 'item',
      width: 220,
      ellipsis: true,
    },
    {
      title: '记分依据',
      dataIndex: 'scoreBasis',
      key: 'scoreBasis',
      width: 220,
      ellipsis: true,
    },
    {
      title: '记分类型',
      dataIndex: 'scoreType',
      key: 'scoreType',
      width: 100,
      ellipsis: true,
    },
    {
      title: '被记分单位',
      dataIndex: 'company',
      key: 'company',
      ellipsis: true,
    },
    {
      title: '被记分人员所属部门',
      dataIndex: 'groupname',
      key: 'groupname',
      width: 180,
      ellipsis: true,
    },
    {
      title: '被记分人员（主责）姓名',
      dataIndex: 'username',
      key: 'username',
      isMain: true,
      width: 190,
      ellipsis: true,
    },
    {
      title: '被记分人员（连带）姓名',
      dataIndex: 'username',
      key: 'username',
      isMain: false,
      width: 190,
      ellipsis: true,
    },
    {
      title: '分值',
      dataIndex: 'score',
      key: 'score',
      width: 50,
      ellipsis: true,
    },
    {
      title: '审批人',
      dataIndex: 'approvePerson',
      key: 'approvePerson',
      width: 120,
      ellipsis: true,
    },
    {
      title: '审批时间',
      dataIndex: 'approverTime',
      key: 'approverTime',
      width: 200,
      ellipsis: true,
    },
    {
      title: '当前状态',
      dataIndex: 'status',
      key: 'status',
      width: 120,
      ellipsis: true,
    },
    {
      title: '发起记分部门',
      dataIndex: 'initiateGroupname',
      key: 'initiateGroupname',
      ellipsis: true,
    },
    {
      title: '发起记分人员属性',
      dataIndex: 'initiateScoreUserAttribute',
      key: 'initiateScoreUserAttribute',
      ellipsis: true,
    },
    {
      title: '操作',
      dataIndex: 'opr',
      key: 'opr',
      width: 80,
      btns: [
        {
          state: 'detail',
          name: '明细',
        },
      ],
      ellipsis: true,
    },
  ],
  rowKey: 'gid',
  dataSource: [
    {
      gid: 13620,
      role: null,
      finetype: '安全事件',
      scoreSource: '项目公司记分',
      item: '测试',
      dutyType: '主责',
      status: '审核中',
      award: 0,
      fine: 300,
      isfeedback: 0,
      isvisible: 0,
      initiateScoreCompany: 'xxx公司',
      initiateScoreCompanyid: 20,
      initiateScoreUsername: '管理员',
      initiateScoreUserid: 20,
      initiateScoreUsercode: 'admin',
      initiateScoreUserAttribute: '安全监察人员',
      company: 'xxx公司',
      companyid: 36413,
      groupname: 'xxx公司',
      groupid: 36413,
      username: '孙亮平',
      userid: 118695,
      isfine: 0,
      isaward: 0,
      initiateScore: '2025-05-21',
      scoreBasis: '安全事件',
      fullPathScoreBasis: 'LPG业务/安全事件/',
      scoreBasisCode: '100202',
      scoreType: '客服',
      scoreTypeCode: '1002002',
      score: 3,
      createtime: '2025-05-21 19:58:01',
      updatetime: '2025-05-21 19:58:19',
      attach: '682dbfbd00c2695b2c0a733f',
      usercode: '141955406523121566',
      chengranCompany: '',
      chengranCompanyid: null,
      applicantOrgID: 0,
      initiateChengranCompany: '',
      initiateChengranCompanyid: null,
      userAttribute: '中基层员工',
      eventScoreAttribute: null,
      eventScoreAttributeCode: null,
      secondaryScoreAttributeCode: null,
      secondaryScoreAttribute: null,
      initiateGroupname: 'xxx公司',
      approverTime: null,
      approver: 'dinggl',
      approvePerson: '丁桂林',
      processId: '79ab6f71-7235-4336-8f25-ebd72f81f551',
      formdata: null,
      attachments: null,
      initiateGroupid: 20,
      grouptype: 4,
      changApprover: false,
    },
    {
      gid: 13597,
      role: null,
      finetype: '安全事件',
      scoreSource: '安全监察记分',
      item: '安全监察',
      dutyType: '连带',
      status: '审核中',
      award: 0,
      fine: 400,
      isfeedback: 0,
      isvisible: 0,
      initiateScoreCompany: 'xxx公司',
      initiateScoreCompanyid: 36413,
      initiateScoreUsername: '刘慧琴',
      initiateScoreUserid: 112212,
      initiateScoreUsercode: '286156050420999109',
      initiateScoreUserAttribute: '五大安全监察中心及总部',
      company: 'xxx公司',
      companyid: 36413,
      groupname: 'xxx公司',
      groupid: 36413,
      username: '刘鸣',
      userid: 112204,
      isfine: 0,
      isaward: 0,
      initiateScore: '2025-04-10',
      scoreBasis: '安全事件',
      fullPathScoreBasis: '天然气业务/安全事件/',
      scoreBasisCode: '100102',
      scoreType: '运营',
      scoreTypeCode: '1001001',
      score: 4,
      createtime: '2025-04-10 20:46:33',
      updatetime: '2025-04-10 20:47:01',
      attach: '67f7bda7ffb9842678552f07',
      usercode: '0243082821691979',
      chengranCompany: '',
      chengranCompanyid: null,
      applicantOrgID: 0,
      initiateChengranCompany: '',
      initiateChengranCompanyid: null,
      userAttribute: '中基层员工',
      eventScoreAttribute: null,
      eventScoreAttributeCode: null,
      secondaryScoreAttributeCode: null,
      secondaryScoreAttribute: null,
      initiateGroupname: 'xxx公司',
      approverTime: null,
      approver: 'dinggl',
      approvePerson: '丁桂林',
      processId: 'f920da7f-9ef4-4bf2-b1d8-e613b6dc6e69',
      formdata: null,
      attachments: null,
      initiateGroupid: 36413,
      grouptype: 4,
      changApprover: false,
    },
    {
      gid: 13596,
      role: null,
      finetype: '安全事件',
      scoreSource: '安全监察记分',
      item: '安全监察',
      dutyType: '主责',
      status: '审核中',
      award: 0,
      fine: 2400,
      isfeedback: 0,
      isvisible: 0,
      initiateScoreCompany: 'xxx公司',
      initiateScoreCompanyid: 36413,
      initiateScoreUsername: '刘慧琴',
      initiateScoreUserid: 112212,
      initiateScoreUsercode: '286156050420999109',
      initiateScoreUserAttribute: '五大安全监察中心及总部',
      company: 'xxx公司',
      companyid: 36413,
      groupname: 'xxx公司',
      groupid: 36413,
      username: '孙亮平',
      userid: 118695,
      isfine: 0,
      isaward: 0,
      initiateScore: '2025-04-10',
      scoreBasis: '通气点火前，未进行气密性检测或检测不合格仍通气点火。',
      fullPathScoreBasis: '天然气业务/违章/恶性违章/通气点火前，未进行气密性检测或检测不合格仍通气点火。/',
      scoreBasisCode: '10010301002',
      scoreType: '工程',
      scoreTypeCode: '1001003',
      score: 12,
      createtime: '2025-04-10 20:46:33',
      updatetime: '2025-04-10 20:48:39',
      attach: '67f7bda7ffb9842678552f07',
      usercode: '141955406523121566',
      chengranCompany: '',
      chengranCompanyid: null,
      applicantOrgID: 0,
      initiateChengranCompany: '',
      initiateChengranCompanyid: null,
      userAttribute: '中基层员工',
      eventScoreAttribute: null,
      eventScoreAttributeCode: null,
      secondaryScoreAttributeCode: '1001001',
      secondaryScoreAttribute: '主责人员',
      initiateGroupname: 'xxx公司',
      approverTime: '2025-04-10 20:48:11',
      approver: 'dinggl',
      approvePerson: '丁桂林',
      processId: 'b754996d-11bc-459a-bcfc-197894e24024',
      formdata: null,
      attachments: null,
      initiateGroupid: 36413,
      grouptype: 4,
      changApprover: false,
    },
    {
      gid: 13595,
      role: null,
      finetype: '一般违章',
      scoreSource: '项目公司记分',
      item: '孙亮平',
      dutyType: '主责',
      status: '审核中',
      award: 300,
      fine: 600,
      isfeedback: 0,
      isvisible: 0,
      initiateScoreCompany: 'xxx公司',
      initiateScoreCompanyid: 36413,
      initiateScoreUsername: '刘慧琴',
      initiateScoreUserid: 112212,
      initiateScoreUsercode: '286156050420999109',
      initiateScoreUserAttribute: '经管层',
      company: 'xxx公司',
      companyid: 36413,
      groupname: 'xxx公司',
      groupid: 36413,
      username: '孙亮平',
      userid: 118695,
      isfine: 0,
      isaward: 0,
      initiateScore: '2025-04-10',
      scoreBasis: '在易燃易爆场所进行高危作业时，未穿防静电工作服及防静电工作鞋或未使用防爆型低压灯具及防爆工具。',
      fullPathScoreBasis:
        '天然气业务/违章/严重违章/在易燃易爆场所进行高危作业时，未穿防静电工作服及防静电工作鞋或未使用防爆型低压灯具及防爆工具。/',
      scoreBasisCode: '10010302006',
      scoreType: '客服',
      scoreTypeCode: '1001002',
      score: 6,
      createtime: '2025-04-10 20:42:38',
      updatetime: '2025-04-10 20:45:41',
      attach: '67f7bcbcffb9842678552f05',
      usercode: '141955406523121566',
      chengranCompany: '',
      chengranCompanyid: null,
      applicantOrgID: 0,
      initiateChengranCompany: '',
      initiateChengranCompanyid: null,
      userAttribute: '中基层员工',
      eventScoreAttribute: '间接责任人',
      eventScoreAttributeCode: '1002',
      secondaryScoreAttributeCode: null,
      secondaryScoreAttribute: null,
      initiateGroupname: 'xxx公司',
      approverTime: '2025-04-10 20:45:17',
      approver: 'yelong',
      approvePerson: '叶龙',
      processId: '7043567a-9e44-49ef-8457-be05a1b9cff0',
      formdata: null,
      attachments: null,
      initiateGroupid: 36413,
      grouptype: 4,
      changApprover: false,
    },
    {
      gid: 13594,
      role: null,
      finetype: '一般违章',
      scoreSource: '业务监察记分',
      item: '测试业务监察',
      dutyType: '连带',
      status: '已撤回',
      award: 0,
      fine: 300,
      isfeedback: 0,
      isvisible: 0,
      initiateScoreCompany: 'xxx公司',
      initiateScoreCompanyid: 36413,
      initiateScoreUsername: '刘慧琴',
      initiateScoreUserid: 112212,
      initiateScoreUsercode: '286156050420999109',
      initiateScoreUserAttribute: '五大安全监察中心及总部',
      company: 'xxx公司',
      companyid: 36413,
      groupname: 'xxx公司',
      groupid: 36413,
      username: '刘鸣',
      userid: 112204,
      isfine: 0,
      isaward: 0,
      initiateScore: '2025-04-10',
      scoreBasis: '通气点火时用户现场存在隐患或用户拒绝整改给与通气的。',
      fullPathScoreBasis: '客户服务/安全类/严重违规行为/通气点火时用户现场存在隐患或用户拒绝整改给与通气的。/',
      scoreBasisCode: '1007001002001',
      scoreType: '运营',
      scoreTypeCode: '1007001',
      score: 3,
      createtime: '2025-04-10 20:40:54',
      updatetime: '2025-04-10 20:41:21',
      attach: '67f7bc4affb9842678552f03',
      usercode: '0243082821691979',
      chengranCompany: '',
      chengranCompanyid: null,
      applicantOrgID: 0,
      initiateChengranCompany: '',
      initiateChengranCompanyid: null,
      userAttribute: '中基层员工',
      eventScoreAttribute: null,
      eventScoreAttributeCode: null,
      secondaryScoreAttributeCode: '1007002',
      secondaryScoreAttribute: '部门负责人',
      initiateGroupname: 'xxx公司',
      approverTime: '2025-04-10 20:41:26',
      approver: 'yelong;yelong',
      approvePerson: '叶龙,叶龙',
      processId: 'b27433a5-28a2-43a8-9180-d9becfb226f4',
      formdata: null,
      attachments: null,
      initiateGroupid: 36413,
      grouptype: 4,
      changApprover: false,
    },
  ],
  width: null,
  props: {
    size: 'default',
    bordered: false,
    scroll: {
      y: 'calc(100% - 43px)',
    },
  },
};
const page = {
  current: 1,
  pageSize: 20,
  total: 8817,
  onChange: (page, pageSize) => {},
  setSize: (page, pageSize) => {},
  sizeList: ['10', '20', '40', '50'],
};

const View = () => {
  const tableProps = {
    btns,
    table,
    page,
  };

  return <TableCtrl {...tableProps} />;
};

export default View;
