/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/cases/case1': RouteRecordInfo<'/cases/case1', '/cases/case1', Record<never, never>, Record<never, never>>,
    '/cases/case2': RouteRecordInfo<'/cases/case2', '/cases/case2', Record<never, never>, Record<never, never>>,
    '/cases/case3': RouteRecordInfo<'/cases/case3', '/cases/case3', Record<never, never>, Record<never, never>>,
    '/cases/case4': RouteRecordInfo<'/cases/case4', '/cases/case4', Record<never, never>, Record<never, never>>,
    '/fundamentals/easing/': RouteRecordInfo<'/fundamentals/easing/', '/fundamentals/easing', Record<never, never>, Record<never, never>>,
    '/fundamentals/timeline/': RouteRecordInfo<'/fundamentals/timeline/', '/fundamentals/timeline', Record<never, never>, Record<never, never>>,
    '/fundamentals/timeline/control': RouteRecordInfo<'/fundamentals/timeline/control', '/fundamentals/timeline/control', Record<never, never>, Record<never, never>>,
    '/fundamentals/timeline/position': RouteRecordInfo<'/fundamentals/timeline/position', '/fundamentals/timeline/position', Record<never, never>, Record<never, never>>,
    '/fundamentals/tween/': RouteRecordInfo<'/fundamentals/tween/', '/fundamentals/tween', Record<never, never>, Record<never, never>>,
  }
}
