/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/d3//': RouteRecordInfo<'/d3//', '/d3', Record<never, never>, Record<never, never>>,
    '/d3/AboutView': RouteRecordInfo<'/d3/AboutView', '/d3/AboutView', Record<never, never>, Record<never, never>>,
    '/d3/HomeView': RouteRecordInfo<'/d3/HomeView', '/d3/HomeView', Record<never, never>, Record<never, never>>,
    '/svg//': RouteRecordInfo<'/svg//', '/svg', Record<never, never>, Record<never, never>>,
    '/svg/AboutView': RouteRecordInfo<'/svg/AboutView', '/svg/AboutView', Record<never, never>, Record<never, never>>,
    '/svg/HomeView': RouteRecordInfo<'/svg/HomeView', '/svg/HomeView', Record<never, never>, Record<never, never>>,
  }
}
